// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CreateGuestSession(arg1:string):Promise<string>;

export function StartGoogleLogin():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
