// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateGuestSession(arg1) {
  return window['go']['services']['AuthService']['CreateGuestSession'](arg1);
}

export function StartGoogleLogin() {
  return window['go']['services']['AuthService']['StartGoogleLogin']();
}

export function Startup(arg1) {
  return window['go']['services']['AuthService']['Startup'](arg1);
}
