// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function CreateEvent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<services.CEvent>>;

export function GetEvents():Promise<Array<services.CEvent>>;

export function Startup(arg1:context.Context):Promise<void>;
