// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEvent(arg1, arg2, arg3, arg4) {
  return window['go']['services']['CalendarService']['CreateEvent'](arg1, arg2, arg3, arg4);
}

export function GetEvents() {
  return window['go']['services']['CalendarService']['GetEvents']();
}

export function Startup(arg1) {
  return window['go']['services']['CalendarService']['Startup'](arg1);
}
