// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function CreateProject(arg1:string):Promise<Array<services.Project>>;

export function DeleteProject(arg1:string):Promise<Array<services.Project>>;

export function GetProjects():Promise<Array<services.Project>>;

export function Startup(arg1:context.Context):Promise<void>;
