// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1) {
  return window['go']['services']['ProjectService']['CreateProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['services']['ProjectService']['DeleteProject'](arg1);
}

export function GetProjects() {
  return window['go']['services']['ProjectService']['GetProjects']();
}

export function Startup(arg1) {
  return window['go']['services']['ProjectService']['Startup'](arg1);
}
