// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1, arg2) {
  return window['go']['services']['TaskService']['CreateTask'](arg1, arg2);
}

export function DeleteTask(arg1) {
  return window['go']['services']['TaskService']['DeleteTask'](arg1);
}

export function GetTasks() {
  return window['go']['services']['TaskService']['GetTasks']();
}

export function Startup(arg1) {
  return window['go']['services']['TaskService']['Startup'](arg1);
}

export function ToggleTask(arg1) {
  return window['go']['services']['TaskService']['ToggleTask'](arg1);
}
