// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function CreateTask(arg1:string,arg2:string):Promise<Array<services.Task>>;

export function DeleteTask(arg1:string):Promise<Array<services.Task>>;

export function GetTasks():Promise<Array<services.Task>>;

export function Startup(arg1:context.Context):Promise<void>;

export function ToggleTask(arg1:string):Promise<Array<services.Task>>;
