// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddXP(arg1) {
  return window['go']['services']['UserService']['AddXP'](arg1);
}

export function GetUserProfile() {
  return window['go']['services']['UserService']['GetUserProfile']();
}

export function SetUserName(arg1) {
  return window['go']['services']['UserService']['SetUserName'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['UserService']['Startup'](arg1);
}
