// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function AddXP(arg1:number):Promise<services.UserProfile>;

export function GetUserProfile():Promise<services.UserProfile>;

export function SetUserName(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
